objectTypes:
  AdresseerbaarObject:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      gebruiksdoelen:
        type: String
        multiplicity: 1..*
    relations:
      heeftAlsHoofdadres:
        target: Nummeraanduiding
        multiplicity: 1
        inverseName: isHoofdadresVan
        inverseMultiplicity: 0..1
      heeftAlsNevenadres:
        target: Nummeraanduiding
        multiplicity: 0..*
        inverseName: isNevenadresVan
        inverseMultiplicity: 0..1

  Nummeraanduiding:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      huisnummer:
        type: Integer
        multiplicity: 1
      postcode:
        type: String
        multiplicity: 0..1
