objectTypes:
  NatuurlijkPersoon:
    attributes:
      aNummer:
        type: String
        identifier: true
        multiplicity: 1
      burgerservicenummer:
        type: String
        multiplicity: 1

  Verzamelinkomen:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      belastingjaar:
        type: String
        multiplicity: 1
      waarde:
        type: Integer
        multiplicity: 1
    relations:
      van:
        target: NatuurlijkPersoon
        multiplicity: 1
        inverseName: verzamelinkomen
        inverseMultiplicity: 0..*
