objectTypes:
  OnroerendeZaak:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
    relations:
      zakelijkGerechtigden:
        target: NatuurlijkPersoon
        multiplicity: 0..*

  NatuurlijkPersoon:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      bsn:
        type: String
        multiplicity: 0..1

  LocatieKadastraalObject:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
    relations:
      heeft:
        target: OnroerendeZaak
        multiplicity: 1
        inverseName: locatie
        inverseMultiplicity: 0..*
      betreft:
        target: ObjectlocatieBinnenland
        multiplicity: 1
        inverseName: locatie
        inverseMultiplicity: 0..*

  ObjectlocatieBinnenland:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      adresgegevens:
        type: String
        multiplicity: 1
