objectTypes:
  Persoon:
    attributes:
      burgerservicenummer:
        type: String
        identifier: true
        multiplicity: 1
      naam:
        type: String
        multiplicity: 1
      geboortedatum:
        type: String
        multiplicity: 1
      nummeraanduidingIdentificatie:
        type: String
        multiplicity: 0..1
