objectTypes:
  KadastraalOnroerendeZaak:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      eigenaar:
        type: String
        multiplicity: 0..*
      identificatieNummeraanduiding:
        type: String
        multiplicity: 0..*
      identificatieAdresseerbaarObject:
        type: String
        multiplicity: 0..*
      bewoner:
        type: String
        multiplicity: 0..*
      wozWaarde:
        type: Integer
        multiplicity: 0..1

  Woning:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      huisnummer:
        type: Integer
        multiplicity: 1
      postcode:
        type: String
        multiplicity: 0..1
      heeftWoonfunctie:
        type: Boolean
        multiplicity: 1
      inkomenIAH:
        type: Integer
        multiplicity: 0..1
    relations:
      maaktDeelUitVan:
        target: KadastraalOnroerendeZaak
        multiplicity: 0..*
      heeftBewoner:
        target: Bewoner
        multiplicity: 0..*
      heeftEigenaar:
        target: Eigenaar
        multiplicity: 1..*

  Bewoner:
    attributes:
      bsn:
        type: String
        identifier: true
        multiplicity: 1
      naam:
        type: String
        multiplicity: 1
      leeftijd:
        type: Integer
        multiplicity: 1
      inkomen:
        type: Integer
        multiplicity: 0..1

  Eigenaar:
    attributes:
      bsn:
        type: String
        identifier: true
        multiplicity: 1
      naam:
        type: String
        multiplicity: 1