objectTypes:
  WOZObject:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      adresseerbaarObjectIdentificatie:
        type: String
        multiplicity: 1
      waarde:
        type: Integer
        multiplicity: 1
